### ISSUE TITLE
k8s-minion-manager should show money spent/saved

### ISSUE THREAD

**Issue by shrinandj** [keikoproj/minion-manager#3]
**Is this a BUG REPORT or FEATURE REQUEST?:**
FEATURE REQUEST

**What happened:**
k8s-minion-manager can intelligently switch between spot and on-demand instances. However, it doesn't provide information about how much money has been saved because of it. It will be good if the addon can provide that information.

**What you expected to happen:**
There should be an easy way of seeing the money spent and saved on a per IG basis.

**Comment by edlee2121** [comment]
Instead of trying to show the amount of money saved, we should log the price of spot instances and the number of spot vs. non-spot instances running at a given time.

**Comment by tekenstam** [comment]
Will not do. This project is end-of-life and is no longer maintained/supported.
