### ISSUE TITLE
Will `schedule_instance_termination()` terminate instance just created?

### ISSUE THREAD

**Issue by alantang888** [keikoproj/minion-manager#34]
When I read the `schedule_instance_termination()` in `aws_minion_manager.py`. I found it will terminate instances if not match ASG's `k8s-minion-manager`.
But I didn't found `update_scaling_group()` will update the ASG's `k8s-minion-manager` value.
When spot price over on-demand price. mm will update launch config to use on-demand. And update `lc_info` and `bid_info`.
So I worry will it keep terminate instances just launched after price raised over on-demand price.

**Comment by tekenstam** [comment]
Will not do. This project is end-of-life and is no longer maintained/supported.
