### ISSUE TITLE
Bid threshold should be a parameter

### ISSUE THREAD

**Issue by souzabrunoftw** [keikoproj/minion-manager#36]
Hi, I've done some testing on minion-manager and was really satisfied with the result, thinking about implementing it to production :smile: , but I think a configurable threshold should be added, so we can determine how aggressive we want to be about the prices over OnDemand instances.

Something like:
```python
parser.add_argument("--threshold", default=80, help="Max percentage to pay over OnDemand price")
```

Looking at the code, IMO it's a very simple change and I wonder if you think it's valid or not?
I could submit a PR if you're positive.

Thanks.

**Comment by shrinandj** [comment]
@souzabrunoftw , currently, the mechanism for determining whether to use on-demand or spot instances is pretty basic. Happy to accept PRs about to make the threshold configurable.

**Comment by tekenstam** [comment]
Will not do. This project is end-of-life and is no longer maintained/supported.
