### ISSUE TITLE
Does minion-manager support mixed instance?

### ISSUE THREAD

**Issue by petrukngantuk** [keikoproj/minion-manager#73]
Does minion-manager support mixed instance?

I have cluster that use ASG with mixed instance, on-demand + spot instance [reference](https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-purchase-options.html#asg-allocation-strategies) , I want to use minion-manager to just use to autoscale the spot instance? without touching the on-demand one, does this possible with current minion-manager?

**Comment by shrinandj** [comment]
Not at this point. Minion-manager currently only works with launch-configs which only support a single instance type. Minion-manager will need to start supporting launch-templates and  then based on the state of the ASG, increase/decrease the percentage of spot-instances.
