### ISSUE TITLE
Handle AZ-isolated capacity issues

### ISSUE THREAD

**Issue by backjo** [keikoproj/minion-manager#74]
Occasionally, an AZ may run out of spot capacity. When this happens, an ASG will temporarily spin up instances in other AZs if possible - and later attempt to rebalance instances across all AZs. If an AZ is still out of capacity or close to being out, AWS will still attempt to spin up instances in this AZ. We've noticed a lot of node churn when this happens - nodes are spun up, before being yanked by AWS for `instance-terminated-no-capacity` - it would be nice if minion manager was able suspend `AzRebalance` in these cases to avoid further churn.

**Comment by tekenstam** [comment]
Will not do. This project is end-of-life and is no longer maintained/supported.
